version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/tukutuku/Dockerfile
      target: dev
    image: cambis/namunera-test/web:deno10.6.194.5
    environment:
      - DENO_DIR=/app/.deno
    volumes:
      - .:/app
      - ../backend/node_modules:/backend/node_modules
      - ../backend/themes/app/dist:/backend/themes/app/dist
    ports:
      - "3000:8000"
